### PR TITLE
Fix #23, add utility functions

### LINKED ISSUE #23: Add interpretWithMonadT
You could easily add a generalisation of `interpretWithMonad` to the transformer case:

```haskell
interpretWithMonadT :: (forall x . instr x -> m x) -> ProgramT instr m a -> m a
interpretWithMonadT interpreter = go
  where
    go program = do
      firstInstruction <- viewT program
      case firstInstruction of
        Return a -> return a
        instruction :>>= continuation -> interpreter instruction >>= (go . continuation)
```

### PR DESCRIPTION
**Pull request by turion**
These are a few utility functions that I typically need when I work with `operational`. If you want these, I can document them and clean them up according to whatever style you deem appropriate.

### CODE REVIEW

**Comment by turion** [comment]
See https://github.com/Gabriel439/Haskell-MMorph-Library/issues/11#issuecomment-847002284 why I didn't use `mmorph` here

**Comment by HeinrichApfelmus** [comment]
Thanks Manuel! I'd be happy to take most of them if you could add a little documentation, indeed.

I do not understand the `mmorph` stuff well enough yet, so I'd like to hold off on `hoistProgramT`, `hoistViewT`, and `MFunctor` for this pull request.


One trouble with `unviewT` is that `unviewT . viewT` is not quite the identity — it may add redundant "return"s at the end of the monadic action, e.g. `unviewT (viewT (Instr i)) = Bind (…) (…)`. Since we cannot inspect the function type in the second argument of `Bind`, I do not see a way to prevent this. But it should be documented at least.

I'm also beginning to think that the time is ripe for pattern synonyms (#17), which could eliminate the need for `viewT` and `unviewT` entirely.

  [1]: http://downloads.haskell.org/~ghc/8.10.5/docs/html/users_guide/glasgow_exts.html#pattern-synonyms

**Comment by turion** [comment]
Replaced by https://github.com/HeinrichApfelmus/operational/pull/27

**Comment by turion** [comment]
> Thanks Manuel! I'd be happy to take most of them if you could add a little documentation, indeed.

Awesome :) see #27 which is WIP (I'm still haddocking).

> I do not understand the `mmorph` stuff well enough yet, so I'd like to hold off on `hoistProgramT`, `hoistViewT`, and `MFunctor` for this pull request.

Ok, I'll send a separate well-documented PR for that, hopefully it will be clear enough.

> One trouble with `unviewT` is that `unviewT . viewT` is not quite the identity — it may add redundant "return"s at the end of the monadic action, e.g. `unviewT (viewT (Instr i)) = Bind (…) (…)`. Since we cannot inspect the function type in the second argument of `Bind`, I do not see a way to prevent this. But it should be documented at least.

Yes, I'll document. By the monad laws, I believe `viewT . unviewT = return` and `fmap unviewT . viewT = return` semantically, but they may differ in efficiency, yes.

> I'm also beginning to think that the time is ripe for pattern synonyms (#17), which could eliminate the need for `viewT` and `unviewT` entirely.

They can eliminate the need for `unviewT`, but I don't see how this would go for `viewT`, since it returns a result in the inner monad `m`.

**Pull request closed without merging**
